"""Initial migration

Revision ID: 24e7c41083a9
Revises: 
Create Date: 2025-06-20 09:58:36.568037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e7c41083a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vat', sa.String(), nullable=True),
    sa.Column('vat_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_vat'), 'company', ['vat'], unique=False)
    op.create_index(op.f('ix_company_vat_number'), 'company', ['vat_number'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classifier_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_embedding'), 'events', ['embedding'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_pub_date'), 'events', ['pub_date'], unique=False)
    op.create_index(op.f('ix_events_risk_label'), 'events', ['risk_label'], unique=False)
    op.create_index(op.f('ix_events_section'), 'events', ['section'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_table('raw_docs',
    sa.Column('raw_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('raw_id')
    )
    op.create_index(op.f('ix_raw_docs_raw_id'), 'raw_docs', ['raw_id'], unique=False)
    op.create_index(op.f('ix_raw_docs_source'), 'raw_docs', ['source'], unique=False)
    op.create_index(op.f('ix_raw_docs_status'), 'raw_docs', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('assessment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('turnover', sa.Enum('GREEN', 'ORANGE', 'RED', name='risklevel'), nullable=False),
    sa.Column('shareholding', sa.Enum('GREEN', 'ORANGE', 'RED', name='risklevel'), nullable=False),
    sa.Column('bankruptcy', sa.Enum('GREEN', 'ORANGE', 'RED', name='risklevel'), nullable=False),
    sa.Column('legal', sa.Enum('GREEN', 'ORANGE', 'RED', name='risklevel'), nullable=False),
    sa.Column('corruption', sa.Enum('GREEN', 'ORANGE', 'RED', name='risklevel'), nullable=False),
    sa.Column('overall', sa.Enum('GREEN', 'ORANGE', 'RED', name='risklevel'), nullable=False),
    sa.Column('google_results', sa.String(), nullable=True),
    sa.Column('bing_results', sa.String(), nullable=True),
    sa.Column('gov_results', sa.String(), nullable=True),
    sa.Column('news_results', sa.String(), nullable=True),
    sa.Column('analysis_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_id'), 'assessment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_id'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_raw_docs_status'), table_name='raw_docs')
    op.drop_index(op.f('ix_raw_docs_source'), table_name='raw_docs')
    op.drop_index(op.f('ix_raw_docs_raw_id'), table_name='raw_docs')
    op.drop_table('raw_docs')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_section'), table_name='events')
    op.drop_index(op.f('ix_events_risk_label'), table_name='events')
    op.drop_index(op.f('ix_events_pub_date'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_embedding'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_company_vat_number'), table_name='company')
    op.drop_index(op.f('ix_company_vat'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ### 