"""Update company and assessment schema: use vat as PK and FK, update columns

Revision ID: 9eafedcb0069
Revises: 24e7c41083a9
Create Date: 2025-07-03 04:59:59.069899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eafedcb0069'
down_revision = '24e7c41083a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('company_vat', sa.String(), nullable=False))
    op.add_column('assessment', sa.Column('rss_results', sa.String(), nullable=True))
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.create_foreign_key(None, 'assessment', 'company', ['company_vat'], ['vat'])
    op.drop_column('assessment', 'company_id')
    op.add_column('company', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('company', sa.Column('client_tier', sa.String(), nullable=True))
    op.alter_column('company', 'vat',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_company_id', table_name='company')
    op.drop_index('ix_company_name', table_name='company')
    op.drop_index('ix_company_vat_number', table_name='company')
    op.create_index(op.f('ix_company_client_tier'), 'company', ['client_tier'], unique=False)
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    op.drop_column('company', 'id')
    op.drop_column('company', 'name')
    op.drop_column('company', 'vat_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('vat_number', sa.VARCHAR(), nullable=True))
    op.add_column('company', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('company', sa.Column('id', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_client_tier'), table_name='company')
    op.create_index('ix_company_vat_number', 'company', ['vat_number'], unique=False)
    op.create_index('ix_company_name', 'company', ['name'], unique=False)
    op.create_index('ix_company_id', 'company', ['id'], unique=False)
    op.alter_column('company', 'vat',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('company', 'client_tier')
    op.drop_column('company', 'company_name')
    op.add_column('assessment', sa.Column('company_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.create_foreign_key(None, 'assessment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'assessment', 'company', ['company_id'], ['id'])
    op.drop_column('assessment', 'rss_results')
    op.drop_column('assessment', 'company_vat')
    # ### end Alembic commands ### 