name: Deploy Frontend to Google Cloud Run

on:
  push:
    branches:
      - frontend-deploy
    paths:
      - "bhsi-frontend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Step 4: Build and Push Docker Image to Artifact Registry
      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bhsi/bhsi-frontend:latest ./bhsi-frontend
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bhsi/bhsi-frontend:latest

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bhsi-frontend \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bhsi/bhsi-frontend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 80 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 10 \
            --set-env-vars VITE_API_BASE_URL="https://bhsi-backend-485249399569.europe-west1.run.app/api/v1" \
            --set-env-vars VITE_API_TIMEOUT="30000"

      # Step 6: Get service URL
      - name: Get service URL
        run: |
          echo "Frontend URL: $(gcloud run services describe bhsi-frontend --platform managed --region ${{ secrets.GCP_REGION }} --format='value(status.url)')"
